version: '3.5'

services:
  db:
    container_name: 'lifeinvader-db'
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - 'api-data:/var/lib/postgresql/data'
    restart: always
  app:
    container_name: 'lifeinvader-app'
    image: 'ghcr.io/lssrp/lssrp:main'
    depends_on:
      - db
    environment:
      ALLOWED_HOSTS: 'internet.lss-rp.net'
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - '127.0.0.1:51280:80'
    restart: always

networks:
  default:
    external:
      name: lifeinvader

volumes:
  api-data:
    external: true