# Generated by Django 3.2.8 on 2021-10-22 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("li_mail_app", "0007_alter_email_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginPermissions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("no_license", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
