# Generated by Django 3.2.6 on 2021-08-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lssrp_app", "0002_auto_20210822_2153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mailprofile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
