# Generated by Django 3.2.6 on 2021-08-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lssrp_app", "0003_auto_20210826_0028"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailprofile",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
