# Generated by Django 3.2.6 on 2021-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lssrp_app", "0004_mailprofile_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="sent_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
